sealos load -i /mnt/hgfs/vmware/laf.tar
sealos load -i /mnt/hgfs/vmware/kubernetes.tar
sealos load -i /mnt/hgfs/vmware/kubeblocks.tar
sealos load -i /mnt/hgfs/vmware/nginx.tar
sealos load -i /mnt/hgfs/vmware/cert.tar
sealos load -i /mnt/hgfs/vmware/metrics.tar
sealos load -i /mnt/hgfs/vmware/flannel.tar
sealos load -i /mnt/hgfs/vmware/helm.tar
sealos load -i /mnt/hgfs/vmware/openebs.tar
