sealos load -i /mnt/hgfs/Downloads/laf.tar
sealos load -i /mnt/hgfs/Downloads/kubernetes.tar
sealos load -i /mnt/hgfs/Downloads/kubeblocks.tar
sealos load -i /mnt/hgfs/Downloads/nginx.tar
sealos load -i /mnt/hgfs/Downloads/cert.tar
sealos load -i /mnt/hgfs/Downloads/metrics.tar
sealos load -i /mnt/hgfs/Downloads/flannel.tar
sealos load -i /mnt/hgfs/Downloads/helm.tar
sealos load -i /mnt/hgfs/Downloads/openebs.tar
