sealos load -i /mnt/hgfs/cache/VMware/laf.tar
sealos load -i /mnt/hgfs/cache/VMware/kubernetes.tar
sealos load -i /mnt/hgfs/cache/VMware/kubeblocks.tar
sealos load -i /mnt/hgfs/cache/VMware/nginx.tar
sealos load -i /mnt/hgfs/cache/VMware/cert.tar
sealos load -i /mnt/hgfs/cache/VMware/metrics.tar
sealos load -i /mnt/hgfs/cache/VMware/flannel.tar
sealos load -i /mnt/hgfs/cache/VMware/helm.tar
sealos load -i /mnt/hgfs/cache/VMware/openebs.tar
